### ISSUE TITLE
GetAuthenticatedClient  Serializer:jsonSerializerSettings

### ISSUE THREAD

**Issue by mws580** [microsoftgraph/xamarin-csharp-snippets-sample#8]
The GetAuthenticatedClient gets the following exception

Could not load type of field 'Microsoft.Graph.Serializer:jsonSerializerSettings' (0) due to: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:<none>

**Comment by jasonjoh** [comment]
We're archiving this sample and redirecting folks to https://github.com/microsoftgraph/msgraph-training-xamarin (or the corresponding walkthrough at https://docs.microsoft.com/graph/tutorials/xamarin.
